### ISSUE TITLE
Launch gist in browser

### ISSUE THREAD

**Issue by amyleew** [condemil/Gist#170]
Great option when you've got an open .md in Sublime.

**Comment by rudiedirkx** [comment]
You could install _Markdown Preview_ for that. It parses Markdown and opens the resulting HTML in your default browser.

**Comment by amyleew** [comment]
I use _Markdown Preview_, but would be to launch the published Gist not preview the local file.

**Comment by rudiedirkx** [comment]
You mean it opens the resulting HTML file in ST instead of the browser? I had that too, because we developers open `.html` files in a text editor, not a browser, so the default application is not the browser, but ST.

I changed the default application back to my fav browser, but apparently you can explicitly say which app to use, in Markdown Preview's settings. I haven't tried.

If that's not what you mean, what am I talking about?

**Comment by amyleew** [comment]
@rudiedirkx - Nevermind. Found them :+1:
